### PR TITLE
Fixes #9, RAM calculated incorrectly

### LINKED ISSUE #9: RAM calculated incorrectly
[As reported here](https://github.com/pi-hole/pi-hole/issues/2137), @Twiggy159 is experiencing an issue where the RAM is being calculated negatively.

I'm also experiencing the same issue. When using [this code](https://github.com/jpmck/chronometer2/blob/master/chronometer2.sh#L90), I get a value of `-83.8` because buff/cache isn't being calculated correctly, and for some reason, is also including available in the calculation:

```
              total        used        free      shared  buff/cache   available
Mem:        4019572      283612     1303128       53712     2432832     3652348
Swap:             0           0           0
```

This snippet should provide the correct percentage, which for me is 13:
`awk '/MemTotal:/{total=$2} /MemFree:/{free=$2} /Buffers:/{buffers=$2} /^Cached:/{cached=$2} END {printf "%.0f", (total-free-buffers-cached)*100/total}' /proc/meminfo`

Cheers! :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by zarkmell**
Fixes current RAM calculations, mentioned in [linked issue](https://github.com/jpmck/chronometer2/issues/9).

### CODE REVIEW

**Comment by jpmck** [comment]
This issue has been corrected in [v1.2.2](https://github.com/jpmck/chronometer2/releases/tag/v1.2.2) (see [line 92](https://github.com/jpmck/chronometer2/blob/d911d52dbfa735092d07f292bee8beba9ae5edbd/chronometer2.sh#L92)). However, I did not use all of @bpennypacker's changes in his pull request.

Thanks for the help @zarkmell!

**Comment by evlsmurf** [comment]
will you be using all of his changes in the future?

**Comment by jpmck** [comment]
From @bpennypacker's pull request:
> - Hide the cursor so you don't see it on the display. Restore the cursor if you ctrl+c out of the script. **I implemented this in v1.2.2.**
> - Options to change order and/or hide/show only the information you're interested in. **Not yet, but I was planning on expanding the networking section if DHCP is on to show DHCP info or expand the pihole section if DHCP is off (i.e. show top client, hosts, etc.)**
> - Option to include top client/domain/advertiser in stats **See my comment above.**
> - Option to save the scripts PID to a file on startup **The script's PID is saved to chronometer2.pid on startup by default now.**

So, yes... and no...

**Comment by bpennypacker** [comment]
I'll take a look at v1.2.2 when I get a chance and see if I can put together a new PR with the customizations I made that didn't make it in.

**Comment by evlsmurf** [comment]
Thanks Bruce!

**Pull request closed without merging**
